<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MonsterRaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonsterRaceRepository extends EntityRepository
{
}
