root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sonata_admin_dashboard
        permanent: true

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix:   /

_sonata_admin:
    resource: .
    type:     sonata_admin
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
