services:
    app.admin.monster:
        class: AppBundle\Admin\MonsterAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Monsters" }
        arguments:
            - ~
            - AppBundle\Entity\Monster
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]

    app.admin.monster_class:
        class: AppBundle\Admin\MonsterClassAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Monster Classes" }
        arguments:
            - ~
            - AppBundle\Entity\MonsterClass
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
